#!/bin/bash

# automatically load snd-virmidi
if ! grep -q snd-virmidi /etc/modules;
  then
    printf "\n# jOrgan: automatically load snd-virmidi\nsnd-virmidi\n" >> /etc/modules
    modprobe snd-virmidi
fi

# keep virmidi from being loaded as first soundcard
if ! grep -q snd-virmidi /etc/modprobe.d/alsa-base.conf;
  then
    printf "\n# jOrgan: keep virmidi from being loaded as first soundcard\noptions snd-virmidi index=-2\n" >> /etc/modprobe.d/alsa-base.conf
fi